### ISSUE TITLE
Don't leave me hanging!

### ISSUE THREAD

**Issue by mishak87** [ibuildthecloud/coreos-on-do#5]
I have build some scripts around your awesome script. But ssh keeps me hanging. would it be possible to kill the connection after Restart appears?

**Comment by ibuildthecloud** [comment]
That should be doable.  Let me see what I can do.

**Comment by ibuildthecloud** [comment]
Can you try out https://github.com/ibuildthecloud/coreos-on-do/pull/6 and see if it works for you?

**Comment by mishak87** [comment]
I will this evening 1600GMT or so
